// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoList.Infrastructure;

namespace TodoList.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20210131172242_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("TodoList.Models.TodoListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TodoListItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddDate = new DateTime(2021, 1, 31, 19, 22, 41, 334, DateTimeKind.Local).AddTicks(2954),
                            IsDone = false,
                            Title = "Attend courses"
                        },
                        new
                        {
                            Id = 2,
                            AddDate = new DateTime(2021, 1, 31, 19, 22, 41, 339, DateTimeKind.Local).AddTicks(3938),
                            IsDone = false,
                            Title = "Go to the store"
                        },
                        new
                        {
                            Id = 3,
                            AddDate = new DateTime(2021, 1, 31, 19, 22, 41, 339, DateTimeKind.Local).AddTicks(4033),
                            IsDone = true,
                            Title = "Clean the house"
                        },
                        new
                        {
                            Id = 4,
                            AddDate = new DateTime(2021, 1, 31, 19, 22, 41, 339, DateTimeKind.Local).AddTicks(4042),
                            IsDone = true,
                            Title = "Learn programming"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
